---
title: "Gaussian Process 02"
author: "ynakahashi"
date: "2019/3/12"
output: html_document
---

## 「ガウス過程と機械学習」第3章のグラフ（一部）を作図する②

続き

```{r}
## 数列を適当な刻み幅で生成する
generate_vector <- function(by, from = 1, to = 4) seq(by, from = from, to = to)
```


```{r}
x1 <- generate_vectors(by = 0.5, from = 1, to = 4)
x2 <- generate_vectors(by = 0.5, from = 1, to = 4)

get_cov_mat <- function(x1, x2, theta1 = 1, theta2 = 1) {
   theta1 * exp(-apply(as.matrix(x1), 1, function(x) (x-x2)^2/theta2))
}

K <- get_cov_mat(x1, x2)
K
```


```{r}
n_row <- n_col <- length(x1)
tmp_mat <- matrix(0, nrow = n_row, ncol = n_col)
theta1 <- theta2 <- 1
for (i in 1:n_row) {
   for (j in 1:n_col) {
      tmp_mat[i, j] <- theta1 * exp(-(x1[i] - x2[j])^2/theta2)
   }
}
tmp_mat
```

```{r}
corrplot::corrplot(K, method = "shade")
```




```{r}
# set.seed(123)
n <- 2
mu <- rep(0, n_row)
y <- MASS::mvrnorm(n = 2, mu = mu, Sigma = K)
z <- outer(y[1,], y[2,])
persp(x1, x2, z, theta = 320, phi = 20, expand = 0.4, border = "gray",
      shade = 0.1)
```




https://stackoverflow.com/questions/10357002/create-3d-plot-colored-according-to-the-z-axis?rq=1


```{r}
gen_2dim_plot <- function(by, from = 1, to = 4, n = 2) {
   
   x1 <- generate_vectors(by = by, from = from, to = to)
   x2 <- generate_vectors(by = by, from = from, to = to)
   K <- get_cov_mat_02(x1, x2)

   n_row <- length(x1)
   mu <- rep(0, n_row)
   y <- MASS::mvrnorm(n = n, mu = mu, Sigma = K)
   z <- outer(y[1,], y[2,])
   
   col.pal <- colorRampPalette(rev(rainbow(5)))
   colors <- col.pal(100)
   z.facet.center <- (z[-1, -1] + z[-1, -ncol(z)] + z[-nrow(z), -1] + z[-nrow(z), -ncol(z)])/4
   z.facet.range <- cut(z.facet.center, 100)

   persp(x1, x2, z,
         theta = 320, phi = 20, expand = 0.4, border = "gray",
         shade = 0.1, col = colors[z.facet.range])
}
```



```{r}
gen_2dim_plot(0.05, from = 0, to = 1)
```


```{r}
gen_2dim_plot <- function(by, from = 1, to = 4, n = 2, ...) {
   
   x1 <- generate_vectors(by = by, from = from, to = to)
   x2 <- generate_vectors(by = by, from = from, to = to)
   K <- get_cov_mat_02(x1, x2, theta1 = theta1, theta2 = theta2)
   
   n_row <- length(x1)
   mu <- rep(0, n_row)
   y <- MASS::mvrnorm(n = n, mu = mu, Sigma = K)
   z <- outer(y[1,], y[2,])
   
   col.pal <- colorRampPalette(rev(rainbow(5)))
   colors <- col.pal(100)
   z.facet.center <- (z[-1, -1] + z[-1, -ncol(z)] + z[-nrow(z), -1] + z[-nrow(z), -ncol(z)])/4
   z.facet.range <- cut(z.facet.center, 100)

   persp(x1, x2, z,
         theta = 320, phi = 20, expand = 0.4, border = "gray",
         shade = 0.1, col = colors[z.facet.range])
}
```

```{r}
gen_2dim_plot(0.05, from = 0, to = 4, theta1 = 10, theta2 = 1)
```




```{r}
return_h <- function(h) {
   H <- abs(h)
   x <- seq(-H, H, 1/H)
   h <- sign(x) * x^2
   return(h)
}

return_h(5)

```



---

カーネルを定義
引数の渡し方をもっと工夫したい

```{r}
lin_knl <- function(x1, x2) {
   outer(x1, x2)
}

rbf_knl <- function(x1, x2, theta1 = 1, theta2 = 1) {
   theta1 * exp(-apply(as.matrix(x1), 1, function(x) (x-x2)^2/theta2))
}

exp_knl <- function(x1, x2, theta = 1) {
   exp(-apply(as.matrix(x1), 1, function(x) abs(x-x2)/theta1))
}

prd_knl <- function(x1, x2, theta1 = 1, theta2 = 0.5) {
   exp(theta1 * cos(apply(as.matrix(x1), 1, function(x) abs(x-x2)/theta2)))
}

get_cov_mat <- function(kernel, x1, x2) {
   eval(call(kernel, x1 = x1, x2 = x2))
}

```

```{r}
x1 <- generate_vectors(by = 0.1, from = -4, to = 4)
x2 <- generate_vectors(by = 0.1, from = -4, to = 4)

heatmap(get_cov_mat("lin_knl", x1, x2), Rowv = NA, Colv = NA, revC = T)
heatmap(get_cov_mat("rbf_knl", x1, x2), Rowv = NA, Colv = NA, revC = T)
heatmap(get_cov_mat("exp_knl", x1, x2), Rowv = NA, Colv = NA, revC = T)
heatmap(get_cov_mat("prd_knl", x1, x2), Rowv = NA, Colv = NA, revC = T)
```


```{r}
generate_y <- function(kernel, x1, x2, n = 1) {
   K <- get_cov_mat(kernel, x1, x2)
   n_row <- length(x1)
   mu <- rep(0, n_row)
   MASS::mvrnorm(n = n, mu = mu, Sigma = K)
}
```




```{r}
y <- generate_y("lin_knl", x1, x2, n = 5)
for (i in 1:5) {
   if(i == 1) {
      plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "f(x)",
           xlab = "Linear Kernel", col = i)
      next
   }
   par(new = T)
   plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "",
        xlab = "", col = i)
}
```


```{r}
y <- generate_y("rbf_knl", x1, x2, n = 5)
for (i in 1:5) {
   if(i == 1) {
      plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "f(x)",
           xlab = "RBF Kernel", col = i)
      next
   }
   par(new = T)
   plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "",
        xlab = "", col = i)
}

```

```{r}
y <- generate_y("exp_knl", x1, x2, n = 5)
for (i in 1:5) {
   if(i == 1) {
      plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "f(x)",
           xlab = "Exponential Kernel", col = i)
      next
   }
   par(new = T)
   plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "",
        xlab = "", col = i)
}
```



```{r}
y <- generate_y("prd_knl", x1, x2, n = 5)
for (i in 1:5) {
   if(i == 1) {
      plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "f(x)",
           xlab = "Periodic Kernel", col = i)
      next
   }
   par(new = T)
   plot(x1, y[i, ], type = "l", ylim = c(-4, 4), ylab = "",
        xlab = "", col = i)
}
```




