---
title: "Logistic Regression by optim"
author: "Ynakahashi"
date: "2018/6/29"
output: html_document
---
```{r}
set.seed(123)
x1 <- rnorm(n, 0, 1)
x2 <- rnorm(n, 0, 1)
e  <- rlogis(n)

l <- b0 + x1 * b1 + x2 * b2 + e
p <- exp(l) / (1 + exp(l))

dat <- data.frame(
      y = ifelse(p > th, 1, 0),
      x1 = x1,
      x2 = x2)
```


```{r}
LL <- function(pars, dat){
   b0 <- pars[1]
   b1 <- pars[2]
   b2 <- pars[3]
   l <-  b0 + dat$x1 * b1 + dat$x2 * b2
   # sum(dlogis(l, log = TRUE))
   p <- exp(l) / (1 + exp(l))
   # sum(dat$y * log(p) + log(p))
   # sum(dat$y * log(p) - log(1-p) + log(1-p) + log(p))
   mean(dat$y * log(p) + (1-dat$y) * log(1-p))
}
```


```{r}
pars <- c(1, 2, 3)
LL(pars, dat)
```


```{r}
opt1 <- optim(par = c(0, 0.5, 1), LL, control = list(fnscale = -1), dat = dat)
opt1$par
```



```{r}
# opt2 <- optim(opt1$par, LL, control = list(fnscale=-1),
#               method = "BFGS", hessian = TRUE, dat = dat)
# opt2
```

```{r}
sigmoid <- function(z) {
   g <- 1 / (1 + exp(-z))
   return(g)
}

cost <- function(theta) {
   m <- nrow(dat)
   g <- sigmoid(as.matrix(cbind(1, dat[, -1])) %*% as.matrix(theta))
   J <- (1/m) * sum((-dat$y * log(g)) - ((1 - dat$y) * log(1-g)))
   return(J)
}

opt2 <- optim(par = pars, cost)
opt2$par
```
