---
title: "Logistic vs logit lm"
author: "Ynakahashi"
date: "2018/6/29"
output: html_document
---

## 小ネタ①：ロジスティック回帰は集計値を用いても同じ結果となる

```{r}
tmp <- epitools::expand.table(Titanic)
library(tidyverse)
dat_table <- 
   tmp %>% 
   group_by(Class, Sex, Age) %>% 
   summarise("Yes" = sum(Survived == "Yes"),
             "No" = sum(Survived == "No"))

summary(glm(cbind(Yes, No) ~ ., dat_table, family = binomial("logit")))$coef
summary(glm(Survived ~ ., tmp, family = binomial("logit")))$coef
```

## 小ネタ②：ロジスティック回帰とロジットに対する線形回帰は異なる

```{r}
set.seed(123)
n <- 10000
x1 <- sample(c("A", "B"), n, replace = T)
x1_A <- ifelse(x1 == "A", 1, 0)
x1_B <- ifelse(x1 == "B", 1, 0)
x2 <- sample(c("X", "Y", "Z"), n, replace = T)
x2_X <- ifelse(x2 == "X", 1, 0)
x2_Y <- ifelse(x2 == "Y", 1, 0)
x2_Z <- ifelse(x2 == "Z", 1, 0)

b0 <- 0
b1_B <- 1.0
b2_Y <- 1.5
b2_Z <- 3.0

l <- b0 + x1_B * b1_B + x2_Y * b2_Y + x2_Z * b2_Z
p <- exp(l) / (1 + exp(l))
dat <- data.frame(
   y = rbinom(n, 1, p),
   x1 = x1,
   x2 = x2
)

tmp <- dat %>% 
   group_by(x1, x2) %>% 
   summarise("Yes" = sum(y == 1),
             "No" = sum(y == 0)) %>% 
   mutate(p = Yes / (Yes + No)) %>% 
   mutate(logit = log(p / (1-p)))

summary(glm(y ~ x1 + x2, dat, family = binomial("logit")))$coef
summary(lm(logit ~ x1 + x2, tmp))$coef
```

おまけ

```{r}
summary(glm(y ~ x1 + x2, dat, family = binomial("logit")))$coef
summary(glm(cbind(Yes, No) ~ x1 + x2, tmp, family = binomial("logit")))$coef
```



