---
title: "Smoothing Spline"
output: html_document
---

以下の式を最小化する：

$$
\displaystyle \Sigma_{i}^{n} \left\{ Y_{i} - \hat{f}(x_{i})\right\}^{2} + \lambda \int \hat{f}''(x_{i})^{2}dx 
$$

ここで 

$$
\hat{m} = (\hat{f}(x_{i}), \dots, \hat{f}(x_{n})) 
$$

とすれば、上式の第一項は定数として求めることができる。また第二項は式変形により

$$
\displaystyle \int \hat{f}''(x_{i})^{2} dx = \hat{m}^{T}A\hat{m} 
$$ 

として求めることができるため、 $\hat{m}$ と $A$ を求めれば良いことがわかる。
これらはそれぞれ

$$
\hat{m} = (I + \lambda A)^{-1}Y 
$$

および

$$ 
A = \Delta^{T}W^{-1}\Delta 
$$ 

であり、$ \lambda $ はハイパーパラメータである。また $ \Delta $ は

$$
\Delta_{i,i} = \frac{1}{h_{i}}
$$

$$
\Delta_{i,i+1} = -\frac{1}{h_i} -\frac{1}{h_{i+1}}
$$

$$
\Delta_{i,i+2} = \frac{1}{h_{i+1}}
$$

として求まり、 $ W $ は三重対角行列で各々の要素は：

$$
W_{i-1,i} = W_{i,i-1} = \frac{h_{i}}{6}
$$

$$
W_{i,i} = (h_{i} + h_{i+1}) / 3
$$

で計算される。また

$$
h_{i} = \xi_{i+1} - \xi_{i}
$$

で、$\xi$ は連続するノットまたは $x$ の値。


データを作る。

```{r}
set.seed(123)
x <- sort(runif(10, 1, 10))
y <- sin(x) + rnorm(10, 0, 0.1)
plot(x, y, type = "l")
```

$h$を求める。

```{r}
h <- diff(x)
```

$W$を作る。

```{r}
n <- length(x)
W <- matrix(0, n-2, n-2)
## 二回ループを回した方が早いけどとりあえず
for (i in 1:(n-2)) {
  for (j in 1:(n-2)) {
    if(i == j) {
      W[i, j] <- (h[i] + h[i+1])/3
    } else if((i-j) == 1) {
      W[i, j] <- W[j, i] <- h[i]/6
    } else {
      W[i, j] <- 0
    }
  }
}
```

続いて $\Delta$ を作る。

```{r}
delta <- matrix(0, n-2, n)
for (i in 1:(n-2)) {
  for (j in 1:n) {
    if (i == j) {
      delta[i, j] <- 1/h[i]
    } else if(j == (i+1)) {
      delta[i, j] <- -1/h1[i] -1/h[i+1]
    } else if(j == (i+2)) {
      delta[i, j] <- -1/h[i+1]
    } else {
      delta[i, j] <- 0
    }
  }
}
```


$A$ を作る

```{r}
A <- t(delta) %*% solve(W) %*% delta
```

$$
\hat{m} = (I + \lambda A)^{-1}Y 
$$

```{r}
lambda <- 0.5
m <- solve(diag(n) + lambda * A) %*% y
```


```{r}
plot(x, y, ylim = c(-1.2, 1.2), type = "l", col = 1)
par(new = T)
cnt <- 0
for (i in seq(0, 1, 0.05)){
  cnt <- cnt + 1
  lambda <- i
  m <- solve(diag(n) + i * A) %*% y
  if(cnt == 1) {
    plot(x, m, ylim = c(-1.2, 1.2), type = "l", col = i*10, ylab = "")
    par(new = T)
  } else {
    plot(x, m, ylim = c(-1.2, 1.2), type = "l", col = i*10, axes = F, xlab = "",
         ylab = "")
    par(new = T)
  }
}

```


```{r}
plot(x, y, ylim = c(-1.2, 1.2), type = "l", col = 1)
par(new = T)
cnt <- 0
for (i in seq(1.2, 3, 0.1)) {
  cnt <- cnt + 1
  tmp_ss <- smooth.spline(x, y, df = i)
  if(cnt == 1) {
    plot(tmp_ss$x, tmp_ss$y, ylim = c(-1.2, 1.2), type = "l", col = i)
    par(new = T)
  } else {
    plot(tmp_ss$x, tmp_ss$y, ylim = c(-1.2, 1.2), type = "l", col = i, 
         axes = F, xlab = "", ylab = "")
    par(new = T)
  }
}
```



